#Compiler option
CC=COMPILER_COMMAND

#Standard option
STD=-std=gnu++11

#Compiler flags
CFLAGS=-I. -O3

#Include Eigen Library
EIGEN = -I EIGEN_LOCATION

#Debugging flag
DBG = -ggdb

all: run_test
#Terminate after N errors
ERRORFLG=-fmax-errors=5

run_test: tensor_multiplication.cpp 
	$(CC) $(STD) -o $@ tensor_multiplication.cpp $(CFLAGS) $(EIGEN) $(ERRORFLG) $(DBG)

clean:
	rm *o run_test
